export const USER_ACTION_TYPES = {
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
  DELETE_USER: "DELETE_USER",
  ADD_USER: "ADD_USER",
  GET_SINGLE_USER: "GET_SINGLE_USER",
  UPDATE_USER:"UPDATE_USER"
};
